---
services:
  # A useful container that simply passes through log messages to the console
  # helpful for testing awx/tower logging
  logstash:
    build:
      context: ../
      dockerfile: Dockerfile-logstash
    container_name: tools_logstash_1
    hostname: logstash
    networks:
      - awx
