name: Setup images for AWX
description: Builds new awx_devel image
inputs:
  github-token:
    description: GitHub Token for registry access
    required: true
  private-github-token:
    description: GitHub Token for private repositories
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Get python version from Makefile
      shell: bash
      run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

    - name: Set lower case owner name
      shell: bash
      run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Log in to registry
      shell: bash
      run: |
        echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Add Private github token to requirements_git.credentials.txt
      shell: bash
      run: echo "https://x-access-token:${{ inputs.private-github-token }}@github.com" >> requirements/requirements_git.credentials.txt
      if: ${{ inputs.private-github-token != '' }}

    - name: Pre-pull latest devel image to warm cache
      shell: bash
      run: |
        DEV_DOCKER_TAG_BASE=ghcr.io/${OWNER_LC} \
        COMPOSE_TAG=${{ github.base_ref || github.ref_name }} \
        docker pull -q `make print-DEVEL_IMAGE_NAME`

    - name: Build image for current source checkout
      shell: bash
      run: |
        DEV_DOCKER_TAG_BASE=ghcr.io/${OWNER_LC} \
        COMPOSE_TAG=${{ github.base_ref || github.ref_name }} \
        make docker-compose-build
